tensorflow实战day1

1、数据模型——张量（多维数值阵列），由三个参数描述  阶、形状、数据类型
   i.阶：每个张量的维数

In [19]:
import tensorflow as tf
scalar=tf.constant(100)       #标量
vector=tf.constant([1,2,3,4,5])  #向量
matrix=tf.constant([[1,2,3],
                    [4,5,6]]) #矩阵
cube_matrix=tf.constant([[[1],[2],[3]],
                         [[4],[5],[6]],
                        [[7],[8],[9]]])  #立方阵
print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


    ii.形状（行数和列数）

In [26]:
#scalar.get_shape()  #TensorShape([])
#vector.get_shape()  #TensorShape([Dimension(5)])
#matrix.get_shape()  #TensorShape([Dimension(2), Dimension(3)])
cube_matrix.get_shape()  #TensorShape([Dimension(3), Dimension(3), Dimension(1)])

TensorShape([Dimension(3), Dimension(3), Dimension(1)])

    iii.数据类型
    tf.float32   32位浮点数
    tf.float64   64位浮点数
    tf.int8     8位有符号整数
    tf.int16
    tf.int32
    tf.uint8    8位无符号整数
    tf.string   可变长度字节序列
    tf.bool
    tf.complex64 32位实部，32位虚部
    tf.complex128 64位实部，64位虚部
    tf.qint8    8位有符号整型，在量化型op中使用
    tf.qint32
    tf.quint8

2、numpy入门（tensorflow的数据传递需要通过其API与numpy数组交互完成）
   i.数组（Arrays）
   数组的维度数量也成为数组的秩或阶，数组的形状是一个由整数构成的元组，描述数组不同维度上的大小

In [31]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(type(a))
print(a.shape)
#创建数组

#零矩阵
b=np.zeros((2,2))
#print(b)

c=np.full((2,2),7)
#print(c)
#各元素值为1的矩阵 
d=np.ones((2,2))
#print(d)
#单位矩阵
e=np.eye(3)
#print(e)
#随机数矩阵
f=np.random.random((2,2))
#print(f)


#数组索引
g=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
h=g[:2,1:3] #第一维度取0-1个元素，第二个维度取从第1到第2个元素
#print(h)  

#整型数组索引
j=np.array([0,1,2])
g[np.arange(3),j]+=10
#print(g)

#布尔型数组索引
bool_index=(g>10)
print(bool_index)

#数据类型
print(g.dtype)
k=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],dtype=np.float64)
print(k.dtype)

#数组运算
m=np.array([1,2,3,4,5])
n=np.array([1,2,3,4,5])
print(np.add(m,n))
print(np.subtract(m,n))
print(np.multiply(m,n))  #numpy中的乘法是元素乘，而matlab中是矩阵乘
print(np.divide(m,n))

v=np.array([[[1],[2],[3]],
            [[4],[5],[6]],
            [[7],[8],[9]]])
print(np.reshape(v,(v.shape[0],-1)))
print(v.shape)

<class 'numpy.ndarray'>
(2, 3)
[[ True False False False False]
 [False  True False False False]
 [ True  True  True  True  True]]
int32
float64
[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3, 1)


3、变量
由tf.Variable()创建

In [54]:
value=tf.Variable(0,name="value")
one=tf.constant(1)
new_value=tf.add(one,value)
update_value=tf.assign(value,new_value)  #assign add 操作仅仅是计算图上的节点，在会话运行之前，它们不会执行
initializer=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(initializer)
    print(sess.run(value))
    for i in range (10):
        sess.run(update_value)
        print(sess.run(value))

0
1
2
3
4
5
6
7
8
9
10


4、取回

In [57]:
constanta=tf.constant([100.0])
constantb=tf.constant([200.0])
constantc=tf.constant([2.0])
sum_=tf.add(constanta,constantb)
mul_=tf.multiply(constantb,constantc)
with tf.Session() as  sess:
    result=sess.run([sum_,mul_])
    print(result)

[array([300.], dtype=float32), array([400.], dtype=float32)]


5、注入

In [61]:
a=3
b=2
x=tf.placeholder(tf.float32,shape=(a,b))
y=tf.add(x,x)
data=np.random.random((a,b))
sess=tf.Session()
print(sess.run(y,feed_dict={x:data}))

[[0.05212414 0.26744363]
 [0.44092852 0.81382155]
 [1.5365485  0.90380424]]
